GET http://localhost:5000/api/users/test
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InRlc3QiLCJpZCI6IjYzMmQ3MTZlZTgwMzRhZDE1MzQzMzY0YSIsImlhdCI6MTY2MzkyMzQzNH0.GyrgDSrLEc9TjYLVsBm8Pbo-ERHtmPg_mK4GzuPCbBQ